### ISSUE TITLE
有最低配置要求吗？

### ISSUE THREAD

**Issue by PunkSarich** [ben0oil1/GPT-SoVITS-Server#10]
想部署在轻量云服务器上是不是不太行，2G2核内存直接爆了

**Comment by ben0oil1** [comment]
内存要求高，处理器差结果就是慢，但不会废。
当然，现在手机的性能也比2c2g要高很多

**Comment by PunkSarich** [comment]
> 内存要求高，处理器差结果就是慢，但不会废。 当然，现在手机的性能也比2c2g要高很多


试了下2核2g内存的轻量服务器扛不住，docker进程内存吃爆被killed，2核4g的勉强能跑，不过推理一两句后就容易爆内存了，看来想部署在白嫖的服务器上应该是不现实了，得正儿八经搞个配置好点的服务器
