### ISSUE TITLE
拜托制作一个无cuda依赖纯cpu推理的分支

### ISSUE THREAD

**Issue by mrly2333** [ben0oil1/GPT-SoVITS-Server#7]
我在云服务器(ubuntu22.04，windows server2019)上尝试部署本项目，windows上运行时调用了directml，设备为微软基本显示，但实际上无显卡，内存剩余4g，应该是可以运行的，最后报错run error，而ubuntu中首先我尝试直接在python3.9和3.10中pip install -r (依赖文件)，但在安装了大量无必要的NVIDIA依赖后依然失败，使用conda安装了官方运行环境后任然失败，在有NVIDIA显卡的电脑上可以成功运行，但希望作者可以优化下，感谢

**Comment by ben0oil1** [comment]
你用当前的这个依赖，就不需要CUDA环境啊？
直接CPU就可以推理。
这个都是在arm处理器的手机上可以推理的，肯定不依赖CUDA。

这个**直接可以脱离官方环境**，把训练好的模型放对地方就可以用了

**Comment by mrly2333** [comment]
> 你用当前的这个依赖，就不需要CUDA环境啊？ 直接CPU就可以推理。 这个都是在arm处理器的手机上可以推理的，肯定不依赖CUDA。
> 
> 这个**直接可以脱离官方环境**，把训练好的模型放对地方就可以用了

具体情况不知道，但在另一个issue中寻求到了修改版本，删去了directml相关代码，已正常运行
